//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaTienda
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LaTiendaEntities : DbContext
    {
        public LaTiendaEntities()
            : base("name=LaTiendaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClienteSet> ClienteSet { get; set; }
        public virtual DbSet<ColorSet> ColorSet { get; set; }
        public virtual DbSet<LineaDeVentaSet> LineaDeVentaSet { get; set; }
        public virtual DbSet<MarcaSet> MarcaSet { get; set; }
        public virtual DbSet<ProductoSet> ProductoSet { get; set; }
        public virtual DbSet<PuntoDeVentaSet> PuntoDeVentaSet { get; set; }
        public virtual DbSet<RubroSet> RubroSet { get; set; }
        public virtual DbSet<StockSet> StockSet { get; set; }
        public virtual DbSet<SucursalSet> SucursalSet { get; set; }
        public virtual DbSet<TalleSet> TalleSet { get; set; }
        public virtual DbSet<UsuarioSet> UsuarioSet { get; set; }
        public virtual DbSet<VentaSet> VentaSet { get; set; }
        public virtual DbSet<Comprobante> ComprobanteSet { get; set; }
        public virtual DbSet<CondicionTributaria> CondicionTributariaSet { get; set; }
    }
}
