//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaTienda
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductoSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductoSet()
        {
            this.StockSet = new HashSet<StockSet>();
        }
    
        public int Id { get; set; }
        public long Codigo { get; set; }
        public string Descripcion { get; set; }
        public double Costo { get; set; }
        public int MargenDeGanancia { get; set; }
        public double Iva { get; set; }
        public double NetoGravado { get; set; }
        public int PorcentajeIva { get; set; }
        public double PrecioDeVenta { get; set; }
        public int Rubro_Id { get; set; }
        public int Marca_Id { get; set; }
    
        public virtual MarcaSet MarcaSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockSet> StockSet { get; set; }
        public virtual RubroSet RubroSet { get; set; }
    }
}
